---
name: "Build & publish Docker image"
description: "Builds a Docker image, and then pushes to GHCR"

inputs:
  image:
    description: "Image name (subdir containing Dockerfile)"
    required: true
  version:
    description: "Image version/tag"
    required: true
  target:
    description: "Dockerfile target to build"
    required: false
    default: final
  build-args:
    description: "Build arguments to pass along to Docker"
    required: false
  context:
    description: "Build context path (defaults to the image path)"
    required: false
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Build base image (if needed)
      id: build-base
      uses: ./.github/actions/prebuild-base
      with:
        image: ${{ inputs.image }}
        build-args: ${{ inputs.build-args }}
        platforms: linux/amd64,linux/arm64
    - name: Build & push (multi-arch)
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context != '' && inputs.context || format('./{0}/', inputs.image) }}
        file: ./${{ inputs.image }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}:${{ inputs.version }}
        target: ${{ inputs.target }}
        build-args: ${{ inputs.build-args }}
        build-contexts: ${{ steps.build-base.outputs.build-context }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
