---
name: Build & Publish Web Base

on:
  pull_request:
    paths: &watch_paths
      - '.github/actions/**'
      - '.github/workflows/build-and-publish-web-base.yml'
      - '.github/workflows/internal-build-test-and-publish.yml'
      - 'common/**'
      - 'web-base/**'
      - 'tests/web-base/**'
      - 'tests/run-tests.sh'
  push:
    branches:
      - main
    paths: *watch_paths
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  workflow_dispatch:

jobs:
  build-test-and-publish:
    uses: ./.github/workflows/internal-build-test-and-publish.yml
    strategy:
      matrix:
        version:
          - alpine: '3.22'
            name: latest
        target:
          - secure
          - unsecured
    with:
      image: web-base
      version: ${{ matrix.version.name }}${{ matrix.target == 'secure' && '' || format('-{0}', matrix.target) }}
      target: ${{ matrix.target }}
      build-args: |
        ALPINE_VERSION=${{ matrix.version.alpine }}
