---
name: Build & Publish Payload Base

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-publish-payload-base.yml
      - .github/workflows/internal-build-and-publish.yml
      - 'common/**'
      - 'payload-base/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/internal-build-and-publish.yml
    strategy:
      matrix:
        info:
          - version: lts
            node: lts
    with:
      image: payload-base
      version: ${{ matrix.info.version }}
      build-args: |
        NODE_VERSION=${{ matrix.info.node }}
