---
name: Build & Publish Matomo

on:
  pull_request:
    paths: &watch_paths
      - '.github/actions/**'
      - '.github/workflows/build-and-publish-matomo.yml'
      - '.github/workflows/internal-build-test-and-publish.yml'
      - 'common/**'
      - 'matomo/**'
  push:
    branches:
      - main
    paths: *watch_paths
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  workflow_dispatch:

jobs:
  build-test-and-publish:
    uses: ./.github/workflows/internal-build-test-and-publish.yml
    with:
      image: matomo
      version: latest
      context: .
      run-tests: false
