---
name: Build & Publish Test Postgres with optional TimescaleDB & PostGIS

on:
  pull_request:
    paths: &watch_paths
      - '.github/actions/**'
      - '.github/workflows/build-and-publish-test-postgres.yml'
      - '.github/workflows/internal-build-test-and-publish.yml'
      - 'test-postgres/**'
  push:
    branches:
      - main
    paths: *watch_paths
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  workflow_dispatch:

jobs:
  build-test-and-publish:
    uses: ./.github/workflows/internal-build-test-and-publish.yml
    strategy:
      matrix:
        version:
          - name: 'pg16'
            postgres_image: '16-alpine'
            postgis_version: '3.6.3'
            postgis_sha256: '58ff19ae133e470280efb4949ef92e0364d4c2a66bef8c57e69477348d815ea3'
            timescaledb_version: '2.27.2'
            timescaledb_sha256: 'ba47569618b8b8e6b2d58ee27bb0429b8f7954dac3edbcf1ff6ecd6bdc479316'
        target:
          - name: bare
            suffix:
          - name: postgis
            suffix: -postgis
          - name: postgis-timescaledb
            suffix: -postgis-timescaledb
    with:
      image: test-postgres
      version: ${{ matrix.version.name }}${{ matrix.target.suffix }}
      target: ${{ matrix.target.name }}
      run-tests: false
      build-args: |
        POSTGRES_IMAGE=${{ matrix.version.postgres_image }}
        POSTGIS_VERSION=${{ matrix.version.postgis_version }}
        POSTGIS_SHA256=${{ matrix.version.postgis_sha256 }}
        TIMESCALEDB_VERSION=${{ matrix.version.timescaledb_version }}
        TIMESCALEDB_SHA256=${{ matrix.version.timescaledb_sha256 }}
