---
name: Build & Publish Test NATS

on:
  pull_request:
    paths: &watch_paths
      - '.github/actions/**'
      - '.github/workflows/build-and-publish-test-nats.yml'
      - '.github/workflows/internal-build-test-and-publish.yml'
      - 'test-nats/**'
  push:
    branches:
      - main
    paths: *watch_paths
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  workflow_dispatch:

jobs:
  build-test-and-publish:
    uses: ./.github/workflows/internal-build-test-and-publish.yml
    with:
      image: test-nats
      version: latest
      run-tests: false
