---
name: Build & Publish Nuxt Base

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-publish-nuxt-base.yml
      - .github/workflows/internal-build-and-publish.yml
      - 'common/**'
      - 'nuxt-base/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/internal-build-and-publish.yml
    strategy:
      matrix:
        info:
          - version: lts
            node: lts
            unsecured: false
          - version: lts-unsecured
            node: lts
            unsecured: true
    with:
      image: nuxt-base
      version: ${{ matrix.info.version }}
      build-args: |
        NODE_VERSION=${{ matrix.info.node }}
        UNSECURED=${{ matrix.info.unsecured }}
