---
name: Lint

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint YAML & Dockerfile
    uses: wisemen-digital/devops-github-actions/.github/workflows/lint-yaml-and-docker.yml@main
    with:
      docker-lint-recursive: true
